name: challenge_1_mobile_store_maker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5
  image_picker: ^0.8.4+5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
